### ISSUE TITLE
在调试的时候有很大机率会出现 socket hang up 错误

### ISSUE THREAD

**Issue by SOVLOOKUP** [midwayjs/hooks#109]
调试框架：svelte-kit 
复现仓库：https://github.com/sovlookup/midway-svelte
操作系统：Linux 5.13

```
❯ cnpm run dev

> midway-svelte@0.0.1 dev /home/sovlookup/桌面/秦淮/midway-svelte
> svelte-kit dev


  SvelteKit v1.0.0-next.115

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network


上午10:31:26 [vite] Internal server error: request to http://127.0.0.1:7001/api failed, reason: socket hang up
      at ClientRequest.<anonymous> (/home/sovlookup/桌面/秦淮/midway-svelte/node_modules/_node-fetch@2.6.1@node-fetch/lib/index.js:1461:11)
      at ClientRequest.emit (node:events:394:28)
      at ClientRequest.emit (node:domain:470:12)
      at Socket.socketOnEnd (node:_http_client:471:9)
      at Socket.emit (node:events:406:35)
      at Socket.emit (node:domain:470:12)
      at endReadableNT (node:internal/streams/readable:1329:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:363:5)
    at ChildProcess.target.send (node:internal/child_process:724:16)
    at /home/sovlookup/桌面/秦淮/midway-svelte/node_modules/_@midwayjs_cli-plugin-dev@1.2.71@@midwayjs/cli-plugin-dev/dist/index.js:325:24
    at new Promise (<anonymous>)
    at DevPlugin.getData (/home/sovlookup/桌面/秦淮/midway-svelte/node_modules/_@midwayjs_cli-plugin-dev@1.2.71@@midwayjs/cli-plugin-dev/dist/index.js:318:16)
    at /home/sovlookup/桌面/秦淮/midway-svelte/node_modules/_@midwayjs_serverless-dev-pack@1.2.71@@midwayjs/serverless-dev-pack/dist/common.js:64:16
    at waitDev (/home/sovlookup/桌面/秦淮/midway-svelte/node_modules/_@midwayjs_serverless-dev-pack@1.2.71@@midwayjs/serverless-dev-pack/dist/common.js:39:30)
    at Timeout._onTimeout (/home/sovlookup/桌面/秦淮/midway-svelte/node_modules/_@midwayjs_serverless-dev-pack@1.2.71@@midwayjs/serverless-dev-pack/dist/common.js:49:13)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Emitted 'error' event on ChildProcess instance at:
    at node:internal/child_process:728:35
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! midway-svelte@0.0.1 dev: `svelte-kit dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the midway-svelte@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sovlookup/.npm/_logs/2021-06-18T02_31_27_744Z-debug.log
```

**Comment by Lxxyx** [comment]
@echosoar
