### ISSUE TITLE
创建 api 模版的应用，打包时报错

### ISSUE THREAD

**Issue by dwyanewang** [midwayjs/hooks#195]
Executing task: yarn run build <

yarn run v1.22.10
$ node_modules/.bin/mw build

Error! You can try adding the -V parameter for more information output.      

E:\Dwyanewang\Projects\demo\midway3\hooks-app\midway.config.ts:9
import { defineConfig } from '@midwayjs/hooks';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at requireMod (E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\@midwayjs\hooks\dist\util-0e1ac72a.cjs.dev.js:130:20)
    at getConfigFromFile (E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\@midwayjs\hooks\dist\util-0e1ac72a.cjs.dev.js:121:3)
    at getConfig (E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\@midwayjs\hooks\dist\util-0e1ac72a.cjs.dev.js:99:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
终端进程“C:\WINDOWS\System32\cmd.exe /d /c yarn run build”已终止，退出代码: 1。

**Comment by Lxxyx** [comment]
可以先把 `midway.config.ts` 重命名为 `midway.config.js`。

<details>
<summary>Details</summary>

const { defineConfig }= require('@midwayjs/hooks');

export default defineConfig({
  source: './src',
  build: {
    outDir: './dist',
  },
});


</details>

**Comment by Lxxyx** [comment]
fixed: https://github.com/midwayjs/hooks/pull/212
