### ISSUE TITLE
请问一体化项目的后端是否支持单文件构建部署？

### ISSUE THREAD

**Issue by dainyzyg** [midwayjs/hooks#248]
我按照官方文档标准化项目中的单文件构建部署方式尝试构建midway hooks一体化项目，报错如下：
` ERROR 25248 MidwayDefinitionNotFoundError: MidwayKoaFramework is not valid in current context
    at MidwayContainer.getAsync (C:\Code\online-learning\node_modules\@midwayjs\core\dist\context\container.js:425:19)
    at MidwayFrameworkService.init (C:\Code\online-learning\node_modules\@midwayjs\core\dist\service\frameworkService.js:58:73)
    at ObjectCreator.doInitAsync (C:\Code\online-learning\node_modules\@midwayjs\core\dist\definitions\objectCreator.js:111:30)
    at ManagedResolverFactory.createAsync (C:\Code\online-learning\node_modules\@midwayjs\core\dist\context\managedResolverFactory.js:242:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async initializeGlobalApplicationContext (C:\Code\online-learning\node_modules\@midwayjs\core\dist\setup.js:99:5)
    at async BootstrapStarter.init (C:\Code\online-learning\node_modules\@midwayjs\bootstrap\dist\bootstrap.js:27:35)
    at async Function.run (C:\Code\online-learning\node_modules\@midwayjs\bootstrap\dist\bootstrap.js:102:35) {
  code: 'MIDWAY_10003',
  cause: undefined,
  [Symbol(#NotFoundError)]: Symbol(#NotFoundError)
}`
请问一体化项目的后端是否支持单文件构建部署？

**Comment by Lxxyx** [comment]
有做相关支持，3.0 正式版发布时会一并推出。

https://github.com/midwayjs/hooks/blob/main/packages/hcc/README.md

**Comment by dainyzyg** [comment]
> 有做相关支持，3.0 正式版发布时会一并推出。
> 
> https://github.com/midwayjs/hooks/blob/main/packages/hcc/README.md

非常感谢，请问3.0正式版大概什么时候推出呢？

**Comment by Lxxyx** [comment]
修复完目前社区的 Issue + 测试没问题后会正式发布，预计在 3 月底

**Comment by dainyzyg** [comment]
@Lxxyx 感谢回答，非常期待正式版的到来
