### ISSUE TITLE
一体化vue模板，打包后无法运行

### ISSUE THREAD

**Issue by ouou12138** [midwayjs/hooks#533]
一体化模板clone后无任何修改，打包后无法运行

```bash
PS F:\code\demo\hooks-app> node .\bootstrap.js
2023-09-13 21:22:36,674 ERROR 13472 ReferenceError: document is not defined
    at F:\code\demo\hooks-app\dist\_client\assets\index-92b1b080.js:1:21
    at Object.<anonymous> (F:\code\demo\hooks-app\dist\_client\assets\index-92b1b080.js:1:708)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at CommonJSFileDetector.loadSync (F:\code\demo\hooks-app\node_modules\@midwayjs\core\dist\common\fileDetector.js:75:33)
    at CommonJSFileDetector.run (F:\code\demo\hooks-app\node_modules\@midwayjs\core\dist\common\fileDetector.js:43:25)
2023-09-13 21:22:36,676 INFO 13472 [midway:bootstrap] exit with code:1
```

**Comment by czy88840616** [comment]
参考 https://midwayjs.org/docs/container#%E5%BF%BD%E7%95%A5%E6%89%AB%E6%8F%8F 移除前端代码。
