### ISSUE TITLE
example/vue-faas deploy 报错

### ISSUE THREAD

**Issue by KaneOne** [midwayjs/hooks#69]
发布时报错如下：
ReferenceError: describe is not defined
    at Object.<anonymous> (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\src\apis\lambda\index.test.ts:5:1)
    at Module.o._compile (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\node_modules\jiti\dist\v8cache.js:2:2655)      
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at MidwayContainer.loadDirectory (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\node_modules\@midwayjs\core\dist\context\midwayContainer.js:169:37)
    at MidwayContainer.load (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\node_modules\@midwayjs\core\dist\context\midwayContainer.js:97:18)
    at EmptyFramework.containerDirectoryLoad (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\node_modules\@midwayjs\core\dist\baseFramework.js:128:33)
    at EmptyFramework.initialize (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\node_modules\@midwayjs\core\dist\baseFramework.js:56:20)
    at WebRouterCollector.analyze (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\node_modules\@midwayjs\core\dist\util\webRouterCollector.js:17:13)
    at WebRouterCollector.getFlattenRouterTable (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\node_modules\@midwayjs\core\dist\util\webRouterCollector.js:176:13)
    at Object.analysisDecorator (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\node_modules\@midwayjs\fcli-plugin-package\src\utils.ts:119:18)
    at PackagePlugin.analysisCode (C:\Users\kane\Desktop\Dev\clouddev\vite-vue-koa\node_modules\@midwayjs\fcli-plugin-package\src\index.ts:533:28)
    at CommandCore.execLiftcycle (C:\Users\kane\AppData\Roaming\npm\node_modules\@midwayjs\cli\node_modules\@midwayjs\command-core\src\core.ts:195:11)

demo地址：
https://github.com/KaneOne/midway-vue-faas

**Comment by echosoar** [comment]
Will be fixed  in this pr: https://github.com/midwayjs/cli/pull/72
