### ISSUE TITLE
eggjs 能与 svelte 一同运行吗？

### ISSUE THREAD

**Issue by SOVLOOKUP** [midwayjs/hooks#99]
我尝试将例子中的koa修改为eggjs，出现如下错误，是还没有支持吗？
```
/home/sovlookup/桌面/node/hooks/examples/svelte/src/App.svelte:1
(function (exports, require, module, __filename, __dirname) { <script lang="ts">
                                                              ^

SyntaxError: Unexpected token '<'
    at new Script (node:vm:99:7)
    at p._moduleCompile (/home/sovlookup/桌面/node/hooks/examples/svelte/node_modules/_jiti@1.10.1@jiti/dist/v8cache.js:2:3154)
    at Module.o._compile (/home/sovlookup/桌面/node/hooks/examples/svelte/node_modules/_jiti@1.10.1@jiti/dist/v8cache.js:2:2705)
    at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Object.require.extensions.<computed> [as .js] (/home/sovlookup/桌面/node/hooks/examples/svelte/node_modules/_ts-node@9.1.1@ts-node/src/index.ts:1045:43)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at n (/home/sovlookup/桌面/node/hooks/examples/svelte/node_modules/_jiti@1.10.1@jiti/dist/v8cache.js:2:2472)
    at Object.<anonymous> (/home/sovlookup/桌面/node/hooks/examples/svelte/src/main.ts:1:1)
[ Midway ] start error: Unexpected token '<'
```

**Comment by Lxxyx** [comment]
目前还不支持 Egg.js 哈
